name: shahi
description: "Shahi WebView Application"  # More descriptive description

# Version follows semantic versioning (MAJOR.MINOR.PATCH+BUILD)
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"  # More precise SDK constraint
  flutter: ">=3.16.0"     # Explicit Flutter version constraint

dependencies:
  flutter:
    sdk: flutter

  # WebView and URL handling
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.8.0
  webview_flutter_wkwebview: ^3.0.7
  url_launcher: ^6.1.11

  # Essential utility packages
  flutter_riverpod: ^2.4.9            # For state management
  connectivity_plus: ^5.0.2           # Network connectivity status
  fluttertoast: ^8.2.2               # For toast messages
  shared_preferences: ^2.2.2          # Local storage
  pull_to_refresh: ^2.0.0            # Refresh control for WebView

  # UI components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7                # For SVG support
  adaptive_theme: ^3.1.0             # For theme switching

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1    # For generating app icons

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  android_name: "Pawan Koliwada"  # Add this
  ios_name: "Pawan Koliwada"      # Add this

  # Add these assets if needed
  assets:
    - assets/images/
    - assets/icons/

  # Uncomment and customize if using custom fonts
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
  #       - asset: assets/fonts/YourFont-Bold.ttf
  #         weight: 700